terraform {
  required_version = ">= 1.6.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

resource "local_file" "day_a_summary" {
  filename = "${path.module}/day-a-output.txt"

  content = <<EOT
W9 Day A GitOps CI/CD Lab

This file is generated by Terraform.

Pull Request:
- terraform fmt
- terraform validate
- terraform plan

Merge to main:
- terraform apply
EOT
}
