services:
  app:
    build:
      context: ./app
    container_name: student-web-api
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    ports:
      - "8000:8000"
    volumes:
      - app-logs:/logs
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./config/otel-collector.yml:/etc/otel-collector.yml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: ["-config.file=/etc/promtail/promtail.yml"]
    volumes:
      - ./config/promtail.yml:/etc/promtail/promtail.yml:ro
      - app-logs:/logs:ro
    depends_on:
      - loki
      - app

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml:ro
    ports:
      - "3200:3200"

volumes:
  app-logs:
